// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddEventController from "./add_event_controller"
application.register("add-event", AddEventController)

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import DirectionsController from "./directions_controller"
application.register("directions", DirectionsController)

import EditEventController from "./edit_event_controller"
application.register("edit-event", EditEventController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FlightFormController from "./flight_form_controller"
application.register("flight-form", FlightFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HotelFormController from "./hotel_form_controller"
application.register("hotel-form", HotelFormController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import NewEventsController from "./new_events_controller"
application.register("new-events", NewEventsController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import TripFormController from "./trip_form_controller"
application.register("trip-form", TripFormController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
