// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddEventController from "./add_event_controller"
application.register("add-event", AddEventController)

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import DirectionsController from "./directions_controller"
application.register("directions", DirectionsController)

import DragController from "./drag_controller"
application.register("drag", DragController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FlightFormController from "./flight_form_controller"
application.register("flight-form", FlightFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import NewEventsController from "./new_events_controller"
application.register("new-events", NewEventsController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
